// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/totes/:toteId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/totes/[toteId].get').default>>>>
    }
    '/api/totes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/totes/index.get').default>>>>
    }
  }
}
export {}