/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotesRouteImport } from './routes/totes'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TotesToteIdRouteImport } from './routes/totes_.$toteId'

const TotesRoute = TotesRouteImport.update({
  id: '/totes',
  path: '/totes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TotesToteIdRoute = TotesToteIdRouteImport.update({
  id: '/totes_/$toteId',
  path: '/totes/$toteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/totes': typeof TotesRoute
  '/totes/$toteId': typeof TotesToteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/totes': typeof TotesRoute
  '/totes/$toteId': typeof TotesToteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/totes': typeof TotesRoute
  '/totes_/$toteId': typeof TotesToteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/totes'
    | '/totes/$toteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/totes'
    | '/totes/$toteId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/totes'
    | '/totes_/$toteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TotesRoute: typeof TotesRoute
  TotesToteIdRoute: typeof TotesToteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totes': {
      id: '/totes'
      path: '/totes'
      fullPath: '/totes'
      preLoaderRoute: typeof TotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totes_/$toteId': {
      id: '/totes_/$toteId'
      path: '/totes/$toteId'
      fullPath: '/totes/$toteId'
      preLoaderRoute: typeof TotesToteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TotesRoute: TotesRoute,
  TotesToteIdRoute: TotesToteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
