/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotesRouteImport } from './routes/totes'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TotesToteIdRouteImport } from './routes/totes_.$toteId'

const TotesRoute = TotesRouteImport.update({
  id: '/totes',
  path: '/totes',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TotesToteIdRoute = TotesToteIdRouteImport.update({
  id: '/totes_/$toteId',
  path: '/totes/$toteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/totes': typeof TotesRoute
  '/totes/$toteId': typeof TotesToteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/totes': typeof TotesRoute
  '/totes/$toteId': typeof TotesToteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/totes': typeof TotesRoute
  '/totes_/$toteId': typeof TotesToteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scan' | '/totes' | '/totes/$toteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scan' | '/totes' | '/totes/$toteId'
  id: '__root__' | '/' | '/scan' | '/totes' | '/totes_/$toteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScanRoute: typeof ScanRoute
  TotesRoute: typeof TotesRoute
  TotesToteIdRoute: typeof TotesToteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totes': {
      id: '/totes'
      path: '/totes'
      fullPath: '/totes'
      preLoaderRoute: typeof TotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totes_/$toteId': {
      id: '/totes_/$toteId'
      path: '/totes/$toteId'
      fullPath: '/totes/$toteId'
      preLoaderRoute: typeof TotesToteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScanRoute: ScanRoute,
  TotesRoute: TotesRoute,
  TotesToteIdRoute: TotesToteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
