/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TotesImport } from './routes/totes'
import { Route as ScanImport } from './routes/scan'
import { Route as IndexImport } from './routes/index'
import { Route as TotesNewImport } from './routes/totes_.new'
import { Route as TotesToteIdImport } from './routes/totes_.$toteId'
import { Route as TotesToteIdEditImport } from './routes/totes_.$toteId_.edit'

// Create/Update Routes

const TotesRoute = TotesImport.update({
  id: '/totes',
  path: '/totes',
  getParentRoute: () => rootRoute,
} as any)

const ScanRoute = ScanImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TotesNewRoute = TotesNewImport.update({
  id: '/totes_/new',
  path: '/totes/new',
  getParentRoute: () => rootRoute,
} as any)

const TotesToteIdRoute = TotesToteIdImport.update({
  id: '/totes_/$toteId',
  path: '/totes/$toteId',
  getParentRoute: () => rootRoute,
} as any)

const TotesToteIdEditRoute = TotesToteIdEditImport.update({
  id: '/totes_/$toteId_/edit',
  path: '/totes/$toteId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanImport
      parentRoute: typeof rootRoute
    }
    '/totes': {
      id: '/totes'
      path: '/totes'
      fullPath: '/totes'
      preLoaderRoute: typeof TotesImport
      parentRoute: typeof rootRoute
    }
    '/totes_/$toteId': {
      id: '/totes_/$toteId'
      path: '/totes/$toteId'
      fullPath: '/totes/$toteId'
      preLoaderRoute: typeof TotesToteIdImport
      parentRoute: typeof rootRoute
    }
    '/totes_/new': {
      id: '/totes_/new'
      path: '/totes/new'
      fullPath: '/totes/new'
      preLoaderRoute: typeof TotesNewImport
      parentRoute: typeof rootRoute
    }
    '/totes_/$toteId_/edit': {
      id: '/totes_/$toteId_/edit'
      path: '/totes/$toteId/edit'
      fullPath: '/totes/$toteId/edit'
      preLoaderRoute: typeof TotesToteIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/totes': typeof TotesRoute
  '/totes/$toteId': typeof TotesToteIdRoute
  '/totes/new': typeof TotesNewRoute
  '/totes/$toteId/edit': typeof TotesToteIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/totes': typeof TotesRoute
  '/totes/$toteId': typeof TotesToteIdRoute
  '/totes/new': typeof TotesNewRoute
  '/totes/$toteId/edit': typeof TotesToteIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/totes': typeof TotesRoute
  '/totes_/$toteId': typeof TotesToteIdRoute
  '/totes_/new': typeof TotesNewRoute
  '/totes_/$toteId_/edit': typeof TotesToteIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scan'
    | '/totes'
    | '/totes/$toteId'
    | '/totes/new'
    | '/totes/$toteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scan'
    | '/totes'
    | '/totes/$toteId'
    | '/totes/new'
    | '/totes/$toteId/edit'
  id:
    | '__root__'
    | '/'
    | '/scan'
    | '/totes'
    | '/totes_/$toteId'
    | '/totes_/new'
    | '/totes_/$toteId_/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScanRoute: typeof ScanRoute
  TotesRoute: typeof TotesRoute
  TotesToteIdRoute: typeof TotesToteIdRoute
  TotesNewRoute: typeof TotesNewRoute
  TotesToteIdEditRoute: typeof TotesToteIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScanRoute: ScanRoute,
  TotesRoute: TotesRoute,
  TotesToteIdRoute: TotesToteIdRoute,
  TotesNewRoute: TotesNewRoute,
  TotesToteIdEditRoute: TotesToteIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/scan",
        "/totes",
        "/totes_/$toteId",
        "/totes_/new",
        "/totes_/$toteId_/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/scan": {
      "filePath": "scan.tsx"
    },
    "/totes": {
      "filePath": "totes.tsx"
    },
    "/totes_/$toteId": {
      "filePath": "totes_.$toteId.tsx"
    },
    "/totes_/new": {
      "filePath": "totes_.new.tsx"
    },
    "/totes_/$toteId_/edit": {
      "filePath": "totes_.$toteId_.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
